# Generated by Django 3.1.3 on 2020-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=400)),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=400)),
                ('statecode', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
